// <auto-generated />
using System;
using InvestidorCarteira.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestidorCarteira.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251125140618_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Ativos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoMedio")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAtivo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.ToTable("Ativos");

                    b.HasDiscriminator<string>("TipoAtivo").HasValue("Ativos");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeTitular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Acoes", b =>
                {
                    b.HasBaseType("InvestidorCarteira.Domain.Entities.Ativos");

                    b.HasDiscriminator().HasValue("Acao");
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Criptomoedas", b =>
                {
                    b.HasBaseType("InvestidorCarteira.Domain.Entities.Ativos");

                    b.HasDiscriminator().HasValue("Cripto");
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.ETFs", b =>
                {
                    b.HasBaseType("InvestidorCarteira.Domain.Entities.Ativos");

                    b.HasDiscriminator().HasValue("ETF");
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.FIIs", b =>
                {
                    b.HasBaseType("InvestidorCarteira.Domain.Entities.Ativos");

                    b.HasDiscriminator().HasValue("FII");
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Ativos", b =>
                {
                    b.HasOne("InvestidorCarteira.Domain.Entities.Portfolio", null)
                        .WithMany("Ativos")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("InvestidorCarteira.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
